# Generated by Django 3.0.8 on 2020-09-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='core',
            name='post_image',
            field=models.ImageField(default='', max_length=2083, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='core',
            name='excerpt',
            field=models.CharField(default='sadfsdfs', max_length=200),
            preserve_default=False,
        ),
    ]
