# Generated by Django 3.0.8 on 2020-09-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200909_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='post_image',
            field=models.ImageField(max_length=2083, upload_to='images/'),
        ),
    ]
