# Generated by Django 3.0.8 on 2020-09-09 04:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200909_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilities', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facilities')),
            ],
        ),
        migrations.CreateModel(
            name='LeavingFromPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Places')),
            ],
        ),
        migrations.CreateModel(
            name='MasterSpares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Spare Name')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('Age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('Gender', models.IntegerField(choices=[(1, 'male'), (2, 'Female')], default=1)),
                ('Date_Of_Journey', models.DateField(default=datetime.datetime.now)),
                ('Date_of_return', models.DateField(default=datetime.datetime.now)),
                ('Type_of_vehicle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type of vehicle')),
                ('Additional_feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.MasterSpares')),
                ('Going_To', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Going_To', to='core.LeavingFromPlaces')),
                ('Leaving_From', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Leaving_From', to='core.LeavingFromPlaces')),
                ('services', models.ManyToManyField(blank=True, null=True, to='core.Facility')),
            ],
        ),
    ]
