# Generated by Django 3.0.8 on 2020-09-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_facility_leavingfromplaces_masterspares_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Gender'),
        ),
    ]
