# Generated by Django 3.0.8 on 2020-10-14 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelName', models.CharField(max_length=255)),
                ('Price', models.FloatField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=100)),
                ('slug', models.SlugField(max_length=100, unique_for_date='active')),
            ],
        ),
        migrations.CreateModel(
            name='RoomAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomNumber', models.CharField(max_length=255, unique=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.HotelModel')),
            ],
        ),
        migrations.CreateModel(
            name='GuestReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('mobileNumber', models.IntegerField(unique=True, verbose_name='Mobile No')),
                ('Age', models.IntegerField()),
                ('hotel', models.ForeignKey(default='Hotel Not Defined', on_delete=django.db.models.deletion.PROTECT, to='api.HotelModel')),
                ('roomNumber', models.ForeignKey(default='Rooms not defined', on_delete=django.db.models.deletion.PROTECT, to='api.RoomAvailable')),
            ],
        ),
    ]
