# Generated by Django 3.0.8 on 2020-10-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_hotelmodel_hotelplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelmodel',
            name='hotel_image',
            field=models.ImageField(default='image', max_length=2083, upload_to='images/'),
            preserve_default=False,
        ),
    ]
